name: Run every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    name: Run every 5 minutse
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello World"
